name: meet
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #Firebase core
  firebase_core: ^0.4.0+9
  # Firebase auth
  firebase_auth: ^0.16.1
  # Cloud Firestore
  cloud_firestore: ^0.13.7
  #Firebase Storage - To Store images
  firebase_storage: ^3.1.6
  # Functional Programming
  dartz: ^0.9.1
  # Service locator
  get_it: ^4.0.2
  provider: ^4.3.1
  # Local Data
  shared_preferences: ^0.5.8
  # Fonts
  google_fonts: ^1.1.0
  # Lint rules 
  lint: ^1.2.0
  # Bloc Pattern
  flutter_bloc: ^6.0.1
  equatable: ^1.2.0
  # Network
  data_connection_checker: ^0.3.4
  flutter_offline: ^0.3.0
  # Random number
  random_string: ^2.1.0 
  # Circular check box for sign-up
  circular_check_box: 1.0.1
  # Image picker
  image_picker: ^0.6.7+4
  # Human readable time
  time_formatter: ^1.0.0
  # more icons
  material_design_icons_flutter: ^4.0.5345
  # Image stack
  image_stack: ^1.0.1
  # Date format
  intl: ^0.16.1
  #

  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
